### ISSUE TITLE
Break out work items for updating/improving the ARM templates currently in the Partner Repos

### ISSUE THREAD

**Issue by davymcaleer** [chef-partners/arm-templates#32]
Task to expand create work items for improving and enhancing all the ARM templates already created within the Partner Org

**Comment by davymcaleer** [comment]
@trevorghess can you break out some cards on the Azure Projects Board for the ARM template work so @gavindidrichsen can start working through them and we can have any improvements/enhancements reviewed as he goes?

**Comment by gavindidrichsen** [comment]
Thanks Davy.
